window.appCached = {
    "consoleList": [{
        "id": 1,
        "slug": "nes",
        "description": "Nintendo is a great gaming system. Which was released in 1985.",
        "name": "Nintendo",
        "count": null,
        "metadata": null,
        "createdAt": "2018-01-03T18:27:48.000Z",
        "updatedAt": "2018-01-03T18:27:48.000Z"
    }],
    "topGames": [{
        "id": 1217,
        "slug": "super-mario-bros",
        "rom": 1217,
        "status": "publish",
        "name": "Super Mario Bros",
        "consoleId": 1,
        "description": "Greate game from nintendo",
        "publishDate": null,
        "autoContent": null,
        "viewCount": 2348618,
        "loveCount": 0,
        "rateValue": 3.78484,
        "rateCount": 1134,
        "thumbnail": "https://oldgameshelf.com/roms/nes/super-mario-bros/images/1.png",
        "images": ["https://oldgameshelf.com/roms/nes/super-mario-bros/images/2.png", "https://oldgameshelf.com/roms/nes/super-mario-bros/images/8.png", "https://oldgameshelf.com/roms/nes/super-mario-bros/images/4.png", "https://oldgameshelf.com/roms/nes/super-mario-bros/images/5.png", "https://oldgameshelf.com/roms/nes/super-mario-bros/images/3.png", "https://oldgameshelf.com/roms/nes/super-mario-bros/images/1.png", "https://oldgameshelf.com/roms/nes/super-mario-bros/images/6.png"],
        "hashTags": "nes,mario,super mario",
        "activeAt": null,
        "metadata": ["/roms/nes/super-mario-bros/images/2.png", "/roms/nes/super-mario-bros/images/8.png", "/roms/nes/super-mario-bros/images/4.png", "/roms/nes/super-mario-bros/images/5.png", "/roms/nes/super-mario-bros/images/3.png", "/roms/nes/super-mario-bros/images/1.png", "/roms/nes/super-mario-bros/images/6.png"],
        "createdAt": "2018-01-20T07:08:33.000Z",
        "updatedAt": "2019-03-02T16:07:30.000Z",
        "permalink": "/super-mario-bros-1217.html",
        "console": {
            "id": 1,
            "slug": "nes",
            "description": "Nintendo is a great gaming system. Which was released in 1985.",
            "name": "Nintendo",
            "count": null,
            "metadata": null,
            "createdAt": "2018-01-03T18:27:48.000Z",
            "updatedAt": "2018-01-03T18:27:48.000Z",
            "permalink": "/nes"
        },
        "romUrl": "/roms/nes/super-mario-bros/super-mario-bros.zip"
    }, {
        "id": 1221,
        "slug": "super-mario-bros-3",
        "rom": 1221,
        "status": "publish",
        "name": "Super Mario Bros 3",
        "consoleId": 1,
        "description": "Super Mario Bros 3 online game on mobile: iphone, android",
        "publishDate": null,
        "autoContent": null,
        "viewCount": 369588,
        "loveCount": 0,
        "rateValue": 4.04146,
        "rateCount": 458,
        "thumbnail": "https://oldgameshelf.com/roms/nes/super-mario-bros-3/images/super-mario-bros-3-3.png",
        "images": ["https://oldgameshelf.com/roms/nes/super-mario-bros-3/images/super-mario-bros-3-3.png", "https://oldgameshelf.com/roms/nes/super-mario-bros-3/images/super-mario-bros-3-2.jpg", "https://oldgameshelf.com/roms/nes/super-mario-bros-3/images/super-mario-bros-3-4.png", "https://oldgameshelf.com/roms/nes/super-mario-bros-3/images/super-mario-bros-3-1.png"],
        "hashTags": "nes,mario",
        "activeAt": null,
        "metadata": ["/roms/nes/super-mario-bros-3/images/super-mario-bros-3-3.png", "/roms/nes/super-mario-bros-3/images/super-mario-bros-3-2.jpg", "/roms/nes/super-mario-bros-3/images/super-mario-bros-3-4.png", "/roms/nes/super-mario-bros-3/images/super-mario-bros-3-1.png"],
        "createdAt": "2018-02-05T06:06:22.000Z",
        "updatedAt": "2019-03-02T16:07:06.000Z",
        "permalink": "/super-mario-bros-3-1221.html",
        "console": {
            "id": 1,
            "slug": "nes",
            "description": "Nintendo is a great gaming system. Which was released in 1985.",
            "name": "Nintendo",
            "count": null,
            "metadata": null,
            "createdAt": "2018-01-03T18:27:48.000Z",
            "updatedAt": "2018-01-03T18:27:48.000Z",
            "permalink": "/nes"
        },
        "romUrl": "/roms/nes/super-mario-bros-3/super-mario-bros-3.zip"
    }, {
        "id": 208,
        "slug": "contra",
        "rom": 208,
        "status": "publish",
        "name": "Contra",
        "consoleId": 1,
        "description": "Contra is among the best nes games of Nintendo gaming system which was release in 1985. #snes[Contra III - The Alien Wars__https://snesnow.com/play/contra-iii-the-alien-wars-239.html]",
        "publishDate": null,
        "autoContent": null,
        "viewCount": 243437,
        "loveCount": 0,
        "rateValue": 3.91135,
        "rateCount": 221,
        "thumbnail": "https://oldgameshelf.com/roms/nes/contra/images/nes_contra_1.jpg",
        "images": ["https://oldgameshelf.com/roms/nes/contra/images/nes_contra_1.jpg", "https://oldgameshelf.com/roms/nes/contra/images/nes_contra_2.jpg"],
        "hashTags": "nes",
        "activeAt": "2018-01-03T18:27:49.000Z",
        "metadata": ["/roms/nes/contra/images/nes_contra_1.jpg", "/roms/nes/contra/images/nes_contra_2.jpg"],
        "createdAt": "2018-01-03T18:27:49.000Z",
        "updatedAt": "2019-03-02T16:07:19.000Z",
        "permalink": "/contra-208.html",
        "console": {
            "id": 1,
            "slug": "nes",
            "description": "Nintendo is a great gaming system. Which was released in 1985.",
            "name": "Nintendo",
            "count": null,
            "metadata": null,
            "createdAt": "2018-01-03T18:27:48.000Z",
            "updatedAt": "2018-01-03T18:27:48.000Z",
            "permalink": "/nes"
        },
        "romUrl": "/roms/nes/contra/contra.zip"
    }, {
        "id": 1224,
        "slug": "donkey-kong-classics",
        "rom": 1224,
        "status": "publish",
        "name": "Donkey Kong Classics",
        "consoleId": 1,
        "description": "Donkey kong classic is a brilliant game of Nintendo system.",
        "publishDate": null,
        "autoContent": null,
        "viewCount": 217323,
        "loveCount": 0,
        "rateValue": 4.08477,
        "rateCount": 59,
        "thumbnail": "https://oldgameshelf.com/roms/nes/donkey-kong/donkey-kong-classics-play-2.png",
        "images": ["https://oldgameshelf.com/roms/nes/donkey-kong/donkey-kong-classics-play.png", "https://oldgameshelf.com/roms/nes/donkey-kong/donkey-kong-classics-play-2.png"],
        "hashTags": "donkey,kong",
        "activeAt": null,
        "metadata": ["/roms/nes/donkey-kong/donkey-kong-classics-play.png", "/roms/nes/donkey-kong/donkey-kong-classics-play-2.png"],
        "createdAt": "2018-06-16T17:22:12.000Z",
        "updatedAt": "2019-03-02T16:06:47.000Z",
        "permalink": "/donkey-kong-classics-1224.html",
        "console": {
            "id": 1,
            "slug": "nes",
            "description": "Nintendo is a great gaming system. Which was released in 1985.",
            "name": "Nintendo",
            "count": null,
            "metadata": null,
            "createdAt": "2018-01-03T18:27:48.000Z",
            "updatedAt": "2018-01-03T18:27:48.000Z",
            "permalink": "/nes"
        },
        "romUrl": "/roms/nes/donkey-kong/donkey-kong.zip"
    }, {
        "id": 750,
        "slug": "pac-man",
        "rom": 748,
        "status": "publish",
        "name": "Pac-Man",
        "consoleId": 1,
        "description": "Pac-Man is among the best nes games of Nintendo gaming system which was release in 1985.",
        "publishDate": null,
        "autoContent": null,
        "viewCount": 216139,
        "loveCount": 0,
        "rateValue": 4.05173,
        "rateCount": 29,
        "thumbnail": "https://oldgameshelf.com/roms/nes/pac-man/images/pac-man-avatar.png",
        "images": ["https://oldgameshelf.com/roms/nes/pac-man/images/pac-man-avatar.png", "https://oldgameshelf.com/roms/nes/pac-man/images/nes_pac-man_2.jpg", "https://oldgameshelf.com/roms/nes/pac-man/images/nes_pac-man_1.jpg"],
        "hashTags": "nes",
        "activeAt": "2018-01-03T18:27:50.000Z",
        "metadata": ["/roms/nes/pac-man/images/pac-man-avatar.png", "/roms/nes/pac-man/images/nes_pac-man_2.jpg", "/roms/nes/pac-man/images/nes_pac-man_1.jpg"],
        "createdAt": "2018-01-03T18:27:50.000Z",
        "updatedAt": "2019-03-02T16:07:38.000Z",
        "permalink": "/pac-man-750.html",
        "console": {
            "id": 1,
            "slug": "nes",
            "description": "Nintendo is a great gaming system. Which was released in 1985.",
            "name": "Nintendo",
            "count": null,
            "metadata": null,
            "createdAt": "2018-01-03T18:27:48.000Z",
            "updatedAt": "2018-01-03T18:27:48.000Z",
            "permalink": "/nes"
        },
        "romUrl": "/roms/nes/pac-man/pac-man.zip"
    }, {
        "id": 1218,
        "slug": "flappy-bird",
        "rom": 1218,
        "status": "publish",
        "name": "Flappy Bird",
        "consoleId": 1,
        "description": "Flappy Bird on the NES, Remix, ",
        "publishDate": null,
        "autoContent": null,
        "viewCount": 168957,
        "loveCount": 0,
        "rateValue": 3.38096,
        "rateCount": 21,
        "thumbnail": "https://oldgameshelf.com/roms/nes/flappy-bird/images/flappy-bird.png",
        "images": ["https://oldgameshelf.com/roms/nes/flappy-bird/images/flappy-bird.png"],
        "hashTags": "nes,neshack",
        "activeAt": null,
        "metadata": ["/roms/nes/flappy-bird/images/flappy-bird.png"],
        "createdAt": "2018-01-22T14:05:32.000Z",
        "updatedAt": "2019-03-02T16:04:15.000Z",
        "permalink": "/flappy-bird-1218.html",
        "console": {
            "id": 1,
            "slug": "nes",
            "description": "Nintendo is a great gaming system. Which was released in 1985.",
            "name": "Nintendo",
            "count": null,
            "metadata": null,
            "createdAt": "2018-01-03T18:27:48.000Z",
            "updatedAt": "2018-01-03T18:27:48.000Z",
            "permalink": "/nes"
        },
        "romUrl": "/roms/nes/flappy-bird/flappy-bird.zip"
    }, {
        "id": 98,
        "slug": "battle-city",
        "rom": 98,
        "status": "publish",
        "name": "Battle City",
        "consoleId": 1,
        "description": "Battle City is among the best nes games of Nintendo gaming system which was release in 1985.",
        "publishDate": null,
        "autoContent": null,
        "viewCount": 135432,
        "loveCount": 0,
        "rateValue": 3.85494,
        "rateCount": 142,
        "thumbnail": "https://oldgameshelf.com/roms/nes/battle-city/images/nes_battle_city_1.jpg",
        "images": ["https://oldgameshelf.com/roms/nes/battle-city/images/nes_battle_city_1.jpg", "https://oldgameshelf.com/roms/nes/battle-city/images/nes_battle_city_2.jpg"],
        "hashTags": "nes",
        "activeAt": "2018-01-03T18:27:49.000Z",
        "metadata": ["/roms/nes/battle-city/images/nes_battle_city_1.jpg", "/roms/nes/battle-city/images/nes_battle_city_2.jpg"],
        "createdAt": "2018-01-03T18:27:49.000Z",
        "updatedAt": "2019-03-02T16:07:22.000Z",
        "permalink": "/battle-city-98.html",
        "console": {
            "id": 1,
            "slug": "nes",
            "description": "Nintendo is a great gaming system. Which was released in 1985.",
            "name": "Nintendo",
            "count": null,
            "metadata": null,
            "createdAt": "2018-01-03T18:27:48.000Z",
            "updatedAt": "2018-01-03T18:27:48.000Z",
            "permalink": "/nes"
        },
        "romUrl": "/roms/nes/battle-city/battle-city.zip"
    }, {
        "id": 840,
        "slug": "road-fighter",
        "rom": 840,
        "status": "publish",
        "name": "Road Fighter",
        "consoleId": 1,
        "description": "Road Fighter is among the best nes games of Nintendo gaming system which was release in 1985.",
        "publishDate": null,
        "autoContent": null,
        "viewCount": 108778,
        "loveCount": 0,
        "rateValue": 3.73528,
        "rateCount": 68,
        "thumbnail": "https://oldgameshelf.com/roms/nes/road-fighter/images/road-fighter-nes.jpg",
        "images": [],
        "hashTags": "nes",
        "activeAt": "2018-01-03T18:27:50.000Z",
        "metadata": [],
        "createdAt": "2018-01-03T18:27:50.000Z",
        "updatedAt": "2019-03-02T16:07:43.000Z",
        "permalink": "/road-fighter-840.html",
        "console": {
            "id": 1,
            "slug": "nes",
            "description": "Nintendo is a great gaming system. Which was released in 1985.",
            "name": "Nintendo",
            "count": null,
            "metadata": null,
            "createdAt": "2018-01-03T18:27:48.000Z",
            "updatedAt": "2018-01-03T18:27:48.000Z",
            "permalink": "/nes"
        },
        "romUrl": "/roms/nes/road-fighter/road-fighter.zip"
    }, {
        "id": 190,
        "slug": "circus-charlie",
        "rom": 190,
        "status": "publish",
        "name": "Circus Charlie",
        "consoleId": 1,
        "description": "Circus Charlie is among the best nes games of Nintendo gaming system which was release in 1985.",
        "publishDate": null,
        "autoContent": null,
        "viewCount": 97306,
        "loveCount": 0,
        "rateValue": 3.48863,
        "rateCount": 88,
        "thumbnail": "https://oldgameshelf.com/roms/nes/circus-charlie/images/nes_circus_charlie_1.jpg",
        "images": ["https://oldgameshelf.com/roms/nes/circus-charlie/images/nes_circus_charlie_1.jpg", "https://oldgameshelf.com/roms/nes/circus-charlie/images/nes_circus_charlie_2.jpg"],
        "hashTags": "nes",
        "activeAt": "2018-01-03T18:27:49.000Z",
        "metadata": ["/roms/nes/circus-charlie/images/nes_circus_charlie_1.jpg", "/roms/nes/circus-charlie/images/nes_circus_charlie_2.jpg"],
        "createdAt": "2018-01-03T18:27:49.000Z",
        "updatedAt": "2019-03-02T16:04:48.000Z",
        "permalink": "/circus-charlie-190.html",
        "console": {
            "id": 1,
            "slug": "nes",
            "description": "Nintendo is a great gaming system. Which was released in 1985.",
            "name": "Nintendo",
            "count": null,
            "metadata": null,
            "createdAt": "2018-01-03T18:27:48.000Z",
            "updatedAt": "2018-01-03T18:27:48.000Z",
            "permalink": "/nes"
        },
        "romUrl": "/roms/nes/circus-charlie/circus-charlie.zip"
    }, {
        "id": 25,
        "slug": "adventure-island-jap",
        "rom": 26,
        "status": "publish",
        "name": "Adventure Island Jap",
        "consoleId": 1,
        "description": "Adventure Island Jap is among the best nes games of Nintendo gaming system which was release in 1985.",
        "publishDate": null,
        "autoContent": null,
        "viewCount": 71958,
        "loveCount": 0,
        "rateValue": 4.03224,
        "rateCount": 62,
        "thumbnail": "https://oldgameshelf.com/roms/images/advisland-5.jpg",
        "images": [],
        "hashTags": "nes",
        "activeAt": "2018-01-03T18:27:49.000Z",
        "metadata": [],
        "createdAt": "2018-01-03T18:27:49.000Z",
        "updatedAt": "2019-03-02T16:07:33.000Z",
        "permalink": "/adventure-island-jap-25.html",
        "console": {
            "id": 1,
            "slug": "nes",
            "description": "Nintendo is a great gaming system. Which was released in 1985.",
            "name": "Nintendo",
            "count": null,
            "metadata": null,
            "createdAt": "2018-01-03T18:27:48.000Z",
            "updatedAt": "2018-01-03T18:27:48.000Z",
            "permalink": "/nes"
        },
        "romUrl": "/roms/nes/adventure-island-jap/adventure-island-jap.zip"
    }, {
        "id": 1223,
        "slug": "excitebike",
        "rom": 1223,
        "status": "publish",
        "name": "Excitebike",
        "consoleId": 1,
        "description": "Excitebike racing nes games, very funny",
        "publishDate": null,
        "autoContent": null,
        "viewCount": 71729,
        "loveCount": 0,
        "rateValue": 3.85418,
        "rateCount": 48,
        "thumbnail": "https://oldgameshelf.com/roms/nes/excitebike/images/excitebike.png",
        "images": ["https://oldgameshelf.com/roms/nes/excitebike/images/excitebike.png", "https://oldgameshelf.com/roms/nes/excitebike/images/excitebike-cover.jpg"],
        "hashTags": "funny,racing",
        "activeAt": null,
        "metadata": ["/roms/nes/excitebike/images/excitebike.png", "/roms/nes/excitebike/images/excitebike-cover.jpg"],
        "createdAt": "2018-03-02T06:06:14.000Z",
        "updatedAt": "2019-03-02T16:02:26.000Z",
        "permalink": "/excitebike-1223.html",
        "console": {
            "id": 1,
            "slug": "nes",
            "description": "Nintendo is a great gaming system. Which was released in 1985.",
            "name": "Nintendo",
            "count": null,
            "metadata": null,
            "createdAt": "2018-01-03T18:27:48.000Z",
            "updatedAt": "2018-01-03T18:27:48.000Z",
            "permalink": "/nes"
        },
        "romUrl": "/roms/nes/excitebike/excitebike.zip"
    }, {
        "id": 141,
        "slug": "bomberman-ii",
        "rom": 133,
        "status": "publish",
        "name": "Bomberman II",
        "consoleId": 1,
        "description": "Bomberman II is among the best nes games of Nintendo gaming system which was release in 1985.",
        "publishDate": null,
        "autoContent": null,
        "viewCount": 69518,
        "loveCount": 0,
        "rateValue": 3.60571,
        "rateCount": 70,
        "thumbnail": "https://oldgameshelf.com/roms/nes/bomberman-ii/images/bom2.png",
        "images": ["https://oldgameshelf.com/roms/nes/bomberman-ii/images/bom1.png", "https://oldgameshelf.com/roms/nes/bomberman-ii/images/bomberman-cover.png", "https://oldgameshelf.com/roms/nes/bomberman-ii/images/bom2.png"],
        "hashTags": "nes",
        "activeAt": "2018-01-03T18:27:49.000Z",
        "metadata": ["/roms/nes/bomberman-ii/images/bom1.png", "/roms/nes/bomberman-ii/images/bomberman-cover.png", "/roms/nes/bomberman-ii/images/bom2.png"],
        "createdAt": "2018-01-03T18:27:49.000Z",
        "updatedAt": "2019-03-02T15:55:13.000Z",
        "permalink": "/bomberman-ii-141.html",
        "console": {
            "id": 1,
            "slug": "nes",
            "description": "Nintendo is a great gaming system. Which was released in 1985.",
            "name": "Nintendo",
            "count": null,
            "metadata": null,
            "createdAt": "2018-01-03T18:27:48.000Z",
            "updatedAt": "2018-01-03T18:27:48.000Z",
            "permalink": "/nes"
        },
        "romUrl": "/roms/nes/bomberman-ii/bomberman-ii.zip"
    }],
    "hotGames": [{
        "id": 155,
        "slug": "captain-america-and-avengers",
        "rom": 154,
        "status": "publish",
        "name": "Captain America and Avengers",
        "consoleId": 1,
        "description": "Captain America and Avengers is among the best nes games of Nintendo gaming system which was release in 1985.",
        "publishDate": null,
        "autoContent": null,
        "viewCount": 9828,
        "loveCount": 0,
        "rateValue": 3.59286,
        "rateCount": 14,
        "thumbnail": "https://oldgameshelf.com/roms/nes/captain-america-and-avengers/captain-america-and-avengers-enter.png",
        "images": ["https://oldgameshelf.com/roms/nes/captain-america-and-avengers/captain-america-and-avengers-play.png", "https://oldgameshelf.com/roms/nes/captain-america-and-avengers/captain-america-and-avengers-enter.png"],
        "hashTags": "nes",
        "activeAt": "2018-01-03T18:27:49.000Z",
        "metadata": ["/roms/nes/captain-america-and-avengers/captain-america-and-avengers-play.png", "/roms/nes/captain-america-and-avengers/captain-america-and-avengers-enter.png"],
        "createdAt": "2018-01-03T18:27:49.000Z",
        "updatedAt": "2019-03-02T16:01:43.000Z",
        "permalink": "/captain-america-and-avengers-155.html",
        "console": {
            "id": 1,
            "slug": "nes",
            "description": "Nintendo is a great gaming system. Which was released in 1985.",
            "name": "Nintendo",
            "count": null,
            "metadata": null,
            "createdAt": "2018-01-03T18:27:48.000Z",
            "updatedAt": "2018-01-03T18:27:48.000Z",
            "permalink": "/nes"
        },
        "romUrl": "/roms/nes/captain-america-and-avengers/captain-america-and-avengers.zip"
    }, {
        "id": 271,
        "slug": "double-dribble",
        "rom": 271,
        "status": "publish",
        "name": "Double Dribble",
        "consoleId": 1,
        "description": "Double Dribble is among the best nes games of Nintendo gaming system which was release in 1985.",
        "publishDate": null,
        "autoContent": null,
        "viewCount": 15612,
        "loveCount": 0,
        "rateValue": 3.68335,
        "rateCount": 24,
        "thumbnail": "https://oldgameshelf.com/roms/nes/double-dribble/images/nes_double_dribble_1.jpg",
        "images": ["https://oldgameshelf.com/roms/nes/double-dribble/images/nes_double_dribble_1.jpg", "https://oldgameshelf.com/roms/nes/double-dribble/images/nes_double_dribble_2.jpg"],
        "hashTags": "nes",
        "activeAt": "2018-01-03T18:27:49.000Z",
        "metadata": ["/roms/nes/double-dribble/images/nes_double_dribble_1.jpg", "/roms/nes/double-dribble/images/nes_double_dribble_2.jpg"],
        "createdAt": "2018-01-03T18:27:49.000Z",
        "updatedAt": "2019-03-02T14:36:44.000Z",
        "permalink": "/double-dribble-271.html",
        "console": {
            "id": 1,
            "slug": "nes",
            "description": "Nintendo is a great gaming system. Which was released in 1985.",
            "name": "Nintendo",
            "count": null,
            "metadata": null,
            "createdAt": "2018-01-03T18:27:48.000Z",
            "updatedAt": "2018-01-03T18:27:48.000Z",
            "permalink": "/nes"
        },
        "romUrl": "/roms/nes/double-dribble/double-dribble.zip"
    }, {
        "id": 559,
        "slug": "kung-fu",
        "rom": 559,
        "status": "publish",
        "name": "Kung Fu",
        "consoleId": 1,
        "description": "Kung Fu is among the best nes games of Nintendo gaming system which was release in 1985.",
        "publishDate": null,
        "autoContent": null,
        "viewCount": 23386,
        "loveCount": 0,
        "rateValue": 3.7174,
        "rateCount": 23,
        "thumbnail": "https://oldgameshelf.com/roms/nes/kung-fu/images/nes_kung_fu_1.jpg",
        "images": ["https://oldgameshelf.com/roms/nes/kung-fu/images/nes_kung_fu_1.jpg", "https://oldgameshelf.com/roms/nes/kung-fu/images/nes_kung_fu_2.jpg"],
        "hashTags": "nes",
        "activeAt": "2018-01-03T18:27:50.000Z",
        "metadata": ["/roms/nes/kung-fu/images/nes_kung_fu_1.jpg", "/roms/nes/kung-fu/images/nes_kung_fu_2.jpg"],
        "createdAt": "2018-01-03T18:27:50.000Z",
        "updatedAt": "2019-03-02T15:35:27.000Z",
        "permalink": "/kung-fu-559.html",
        "console": {
            "id": 1,
            "slug": "nes",
            "description": "Nintendo is a great gaming system. Which was released in 1985.",
            "name": "Nintendo",
            "count": null,
            "metadata": null,
            "createdAt": "2018-01-03T18:27:48.000Z",
            "updatedAt": "2018-01-03T18:27:48.000Z",
            "permalink": "/nes"
        },
        "romUrl": "/roms/nes/kung-fu/kung-fu.zip"
    }, {
        "id": 593,
        "slug": "lode-runner",
        "rom": 593,
        "status": "publish",
        "name": "Lode Runner",
        "consoleId": 1,
        "description": "Lode Runner is among the best nes games of Nintendo gaming system which was release in 1985.",
        "publishDate": null,
        "autoContent": null,
        "viewCount": 41891,
        "loveCount": 0,
        "rateValue": 3.10186,
        "rateCount": 54,
        "thumbnail": "https://oldgameshelf.com/roms/nes/lode-runner/images/nes_lode_runner_2.jpg",
        "images": ["https://oldgameshelf.com/roms/nes/lode-runner/images/nes_lode_runner_2.jpg", "https://oldgameshelf.com/roms/nes/lode-runner/images/nes_lode_runner_1.jpg"],
        "hashTags": "nes",
        "activeAt": "2018-01-03T18:27:50.000Z",
        "metadata": ["/roms/nes/lode-runner/images/nes_lode_runner_2.jpg", "/roms/nes/lode-runner/images/nes_lode_runner_1.jpg"],
        "createdAt": "2018-01-03T18:27:50.000Z",
        "updatedAt": "2019-03-02T16:03:38.000Z",
        "permalink": "/lode-runner-593.html",
        "console": {
            "id": 1,
            "slug": "nes",
            "description": "Nintendo is a great gaming system. Which was released in 1985.",
            "name": "Nintendo",
            "count": null,
            "metadata": null,
            "createdAt": "2018-01-03T18:27:48.000Z",
            "updatedAt": "2018-01-03T18:27:48.000Z",
            "permalink": "/nes"
        },
        "romUrl": "/roms/nes/lode-runner/lode-runner.zip"
    }, {
        "id": 823,
        "slug": "rainbow-islands",
        "rom": 823,
        "status": "publish",
        "name": "Rainbow Islands",
        "consoleId": 1,
        "description": "Rainbow Islands is among the best nes games of Nintendo gaming system which was release in 1985.",
        "publishDate": null,
        "autoContent": null,
        "viewCount": 10841,
        "loveCount": 0,
        "rateValue": 3.54999,
        "rateCount": 10,
        "thumbnail": "https://oldgameshelf.com/roms/nes/rainbow-islands/rainbow-islands-play.png",
        "images": [],
        "hashTags": "nes",
        "activeAt": "2018-01-03T18:27:50.000Z",
        "metadata": {
            "ogTitle": "Play Rainbow Islands in Facebook browser"
        },
        "createdAt": "2018-01-03T18:27:50.000Z",
        "updatedAt": "2019-03-02T14:55:38.000Z",
        "permalink": "/rainbow-islands-823.html",
        "console": {
            "id": 1,
            "slug": "nes",
            "description": "Nintendo is a great gaming system. Which was released in 1985.",
            "name": "Nintendo",
            "count": null,
            "metadata": null,
            "createdAt": "2018-01-03T18:27:48.000Z",
            "updatedAt": "2018-01-03T18:27:48.000Z",
            "permalink": "/nes"
        },
        "romUrl": "/roms/nes/rainbow-islands/rainbow-islands.zip"
    }, {
        "id": 1003,
        "slug": "super-contra",
        "rom": 1003,
        "status": "publish",
        "name": "Super Contra",
        "consoleId": 1,
        "description": "Super Contra is among the best nes games of Nintendo gaming system which was release in 1985.",
        "publishDate": null,
        "autoContent": null,
        "viewCount": 62189,
        "loveCount": 0,
        "rateValue": 3.68394,
        "rateCount": 56,
        "thumbnail": "https://oldgameshelf.com/roms/nes/super-contra/images/nes_super_contra_1.jpg",
        "images": ["https://oldgameshelf.com/roms/nes/super-contra/images/nes_super_contra_1.jpg", "https://oldgameshelf.com/roms/nes/super-contra/images/nes_super_contra_2.jpg"],
        "hashTags": "nes",
        "activeAt": "2018-01-03T18:27:50.000Z",
        "metadata": ["/roms/nes/super-contra/images/nes_super_contra_1.jpg", "/roms/nes/super-contra/images/nes_super_contra_2.jpg"],
        "createdAt": "2018-01-03T18:27:50.000Z",
        "updatedAt": "2019-03-02T15:52:28.000Z",
        "permalink": "/super-contra-1003.html",
        "console": {
            "id": 1,
            "slug": "nes",
            "description": "Nintendo is a great gaming system. Which was released in 1985.",
            "name": "Nintendo",
            "count": null,
            "metadata": null,
            "createdAt": "2018-01-03T18:27:48.000Z",
            "updatedAt": "2018-01-03T18:27:48.000Z",
            "permalink": "/nes"
        },
        "romUrl": "/roms/nes/super-contra/super-contra.zip"
    }, {
        "id": 1054,
        "slug": "teenage-mutant-ninja-turles-3",
        "rom": 1054,
        "status": "publish",
        "name": "Teenage Mutant Ninja Turtles 3",
        "consoleId": 1,
        "description": "Teenage Mutant Ninja Turles 3 is among the best nes games of Nintendo gaming system which was release in 1985.",
        "publishDate": null,
        "autoContent": null,
        "viewCount": 11989,
        "loveCount": 0,
        "rateValue": 4.20001,
        "rateCount": 20,
        "thumbnail": "https://r.mprd.se/fup/up/57217-Teenage_Mutant_Ninja_Turtles_III_-_The_Manhattan_Project_(USA)-1.jpg",
        "images": [],
        "hashTags": "nes",
        "activeAt": "2018-01-03T18:27:50.000Z",
        "metadata": {
            "ogTitle": "Play Teenage Mutant Ninja Turtles 3 on Safari"
        },
        "createdAt": "2018-01-03T18:27:50.000Z",
        "updatedAt": "2019-03-02T15:53:18.000Z",
        "permalink": "/teenage-mutant-ninja-turles-3-1054.html",
        "console": {
            "id": 1,
            "slug": "nes",
            "description": "Nintendo is a great gaming system. Which was released in 1985.",
            "name": "Nintendo",
            "count": null,
            "metadata": null,
            "createdAt": "2018-01-03T18:27:48.000Z",
            "updatedAt": "2018-01-03T18:27:48.000Z",
            "permalink": "/nes"
        },
        "romUrl": "/roms/nes/teenage-mutant-ninja-turles-2/teenage-mutant-ninja-turles-2.zip"
    }, {
        "id": 1206,
        "slug": "yume-penguin-monogatari-japan-tspa10-paladinknights",
        "rom": 1206,
        "status": "publish",
        "name": "Yume Penguin Monogatari (Japan) [T+Spa1.0 PaladinKnights]",
        "consoleId": 1,
        "description": "Yume Penguin Monogatari (Japan) [T+Spa1.0 PaladinKnights] is among the best nes games of Nintendo gaming system which was release in 1985.",
        "publishDate": null,
        "autoContent": null,
        "viewCount": 6242,
        "loveCount": 0,
        "rateValue": 4.4,
        "rateCount": 1,
        "thumbnail": "https://oldgameshelf.com/roms/nes/yume-penguin-monogatari-japan-tspa10-paladinknights/images/nes_yume_penguin_monogatari_(japan)_[t+spa1.jpg",
        "images": ["https://oldgameshelf.com/roms/nes/yume-penguin-monogatari-japan-tspa10-paladinknights/images/nes_yume_penguin_monogatari_(japan)_[t+spa1.jpg"],
        "hashTags": "nes",
        "activeAt": "2018-01-03T18:27:50.000Z",
        "metadata": ["/roms/nes/yume-penguin-monogatari-japan-tspa10-paladinknights/images/nes_yume_penguin_monogatari_(japan)_[t+spa1.jpg"],
        "createdAt": "2018-01-03T18:27:50.000Z",
        "updatedAt": "2019-03-02T08:20:35.000Z",
        "permalink": "/yume-penguin-monogatari-japan-tspa10-paladinknights-1206.html",
        "console": {
            "id": 1,
            "slug": "nes",
            "description": "Nintendo is a great gaming system. Which was released in 1985.",
            "name": "Nintendo",
            "count": null,
            "metadata": null,
            "createdAt": "2018-01-03T18:27:48.000Z",
            "updatedAt": "2018-01-03T18:27:48.000Z",
            "permalink": "/nes"
        },
        "romUrl": "/roms/nes/yume-penguin-monogatari-japan-tspa10-paladinknights/yume-penguin-monogatari-japan-tspa10-paladinknights.zip"
    }, {
        "id": 1219,
        "slug": "ice-climber",
        "rom": 1219,
        "status": "publish",
        "name": "Ice Climber",
        "consoleId": 1,
        "description": "Ice Climber funny multiplayer NES game.",
        "publishDate": null,
        "autoContent": null,
        "viewCount": 21180,
        "loveCount": 0,
        "rateValue": 4.57142,
        "rateCount": 56,
        "thumbnail": "https://oldgameshelf.com/roms/nes/ice-climber/images/ice-climber.png",
        "images": ["https://oldgameshelf.com/roms/nes/ice-climber/images/ice-climber.png"],
        "hashTags": "nes,multiplayer,funny",
        "activeAt": null,
        "metadata": ["/roms/nes/ice-climber/images/ice-climber.png"],
        "createdAt": "2018-01-22T17:06:18.000Z",
        "updatedAt": "2019-03-02T16:07:25.000Z",
        "permalink": "/ice-climber-1219.html",
        "console": {
            "id": 1,
            "slug": "nes",
            "description": "Nintendo is a great gaming system. Which was released in 1985.",
            "name": "Nintendo",
            "count": null,
            "metadata": null,
            "createdAt": "2018-01-03T18:27:48.000Z",
            "updatedAt": "2018-01-03T18:27:48.000Z",
            "permalink": "/nes"
        },
        "romUrl": "/roms/nes/ice-climber/ice-climber.zip"
    }, {
        "id": 1224,
        "slug": "donkey-kong-classics",
        "rom": 1224,
        "status": "publish",
        "name": "Donkey Kong Classics",
        "consoleId": 1,
        "description": "Donkey kong classic is a brilliant game of Nintendo system.",
        "publishDate": null,
        "autoContent": null,
        "viewCount": 217323,
        "loveCount": 0,
        "rateValue": 4.08477,
        "rateCount": 59,
        "thumbnail": "https://oldgameshelf.com/roms/nes/donkey-kong/donkey-kong-classics-play-2.png",
        "images": ["https://oldgameshelf.com/roms/nes/donkey-kong/donkey-kong-classics-play.png", "https://oldgameshelf.com/roms/nes/donkey-kong/donkey-kong-classics-play-2.png"],
        "hashTags": "donkey,kong",
        "activeAt": null,
        "metadata": ["/roms/nes/donkey-kong/donkey-kong-classics-play.png", "/roms/nes/donkey-kong/donkey-kong-classics-play-2.png"],
        "createdAt": "2018-06-16T17:22:12.000Z",
        "updatedAt": "2019-03-02T16:06:47.000Z",
        "permalink": "/donkey-kong-classics-1224.html",
        "console": {
            "id": 1,
            "slug": "nes",
            "description": "Nintendo is a great gaming system. Which was released in 1985.",
            "name": "Nintendo",
            "count": null,
            "metadata": null,
            "createdAt": "2018-01-03T18:27:48.000Z",
            "updatedAt": "2018-01-03T18:27:48.000Z",
            "permalink": "/nes"
        },
        "romUrl": "/roms/nes/donkey-kong/donkey-kong.zip"
    }, {
        "id": 1225,
        "slug": "popeye",
        "rom": 1225,
        "status": "publish",
        "name": "Popeye",
        "consoleId": 1,
        "description": "Good game Popeye",
        "publishDate": null,
        "autoContent": null,
        "viewCount": 16981,
        "loveCount": 0,
        "rateValue": 3.46154,
        "rateCount": 26,
        "thumbnail": "https://oldgameshelf.com/roms/nes/popeye/popeye-cover.jpg",
        "images": ["https://oldgameshelf.com/roms/nes/popeye/popeye-play.png", "https://oldgameshelf.com/roms/nes/popeye/popeye-cover.jpg"],
        "hashTags": "popeye",
        "activeAt": null,
        "metadata": ["https://oldgameshelf.com/roms/nes/popeye/popeye-play.png", "https://oldgameshelf.com/roms/nes/popeye/popeye-cover.jpg"],
        "createdAt": "2018-06-16T17:57:13.000Z",
        "updatedAt": "2019-03-02T13:16:07.000Z",
        "permalink": "/popeye-1225.html",
        "console": {
            "id": 1,
            "slug": "nes",
            "description": "Nintendo is a great gaming system. Which was released in 1985.",
            "name": "Nintendo",
            "count": null,
            "metadata": null,
            "createdAt": "2018-01-03T18:27:48.000Z",
            "updatedAt": "2018-01-03T18:27:48.000Z",
            "permalink": "/nes"
        },
        "romUrl": "/roms/nes/popeye/popeye.zip"
    }, {
        "id": 1226,
        "slug": "legend-of-zelda-2018",
        "rom": 1226,
        "status": "publish",
        "name": "Legend Of Zelda 2018",
        "consoleId": 1,
        "description": "Legend Of Zelda 2018 was released. This is a great game of NES age.",
        "publishDate": null,
        "autoContent": null,
        "viewCount": 34787,
        "loveCount": 0,
        "rateValue": 4.04167,
        "rateCount": 96,
        "thumbnail": "https://oldgameshelf.com/roms/nes/legend-of-zelda/legend-of-zelda-enter.png",
        "images": [],
        "hashTags": "nes",
        "activeAt": null,
        "metadata": {
            "ogTitle": "Legend Of Zelda 2018 NES game"
        },
        "createdAt": "2018-07-11T05:47:53.000Z",
        "updatedAt": "2019-03-02T16:03:44.000Z",
        "permalink": "/legend-of-zelda-2018-1226.html",
        "console": {
            "id": 1,
            "slug": "nes",
            "description": "Nintendo is a great gaming system. Which was released in 1985.",
            "name": "Nintendo",
            "count": null,
            "metadata": null,
            "createdAt": "2018-01-03T18:27:48.000Z",
            "updatedAt": "2018-01-03T18:27:48.000Z",
            "permalink": "/nes"
        },
        "romUrl": "/roms/nes/legend-of-zelda/legend-of-zelda.zip"
    }]
};